name: Deploy NBA Oracle to Azure

on:
  push:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Upload to Azure Blob Storage
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az storage blob upload-batch \
              --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }} \
              --account-key ${{ secrets.AZURE_STORAGE_ACCOUNT_KEY }} \
              --destination '$web' \
              --source . \
              --overwrite true